// V0.3 本地持久存档。localStorage 在同一站点刷新/关闭浏览器后仍保留；另设 resume 存档用于刷新恢复。
export class SaveSystem {
 constructor({maxSlots=3,storagePrefix='frontline-1937-1945-v0.3'}={}){this.maxSlots=maxSlots;this.storagePrefix=storagePrefix;this.autoKey=`${storagePrefix}:autosave`;this.resumeKey=`${storagePrefix}:resume`;}
 clone(v){return JSON.parse(JSON.stringify(v));} key(slot){const n=Math.max(1,Math.min(this.maxSlots,Number(slot)||1));return`${this.storagePrefix}:slot:${n}`;}
 createSnapshot({units,turnSystem,gameState,gameOver,scenario,world,reinforcementSystem}){return{version:'0.3.1',savedAt:new Date().toISOString(),scenarioKey:gameState?.scenarioKey??scenario?.id??null,scenarioName:gameState?.scenarioName??scenario?.name??'战役',playerFaction:gameState?.playerFaction??gameState?.playerSide??null,mode:gameState?.mode??'player',gameOver:gameOver===true,turn:{turn:turnSystem?.turn??1,phase:turnSystem?.phase??null,year:turnSystem?.year??null,month:turnSystem?.month??null,day:turnSystem?.day??null,hour:turnSystem?.hour??null,minute:turnSystem?.minute??null},units:this.clone(units??[]),world:{fortifications:this.clone(world?.fortifications??[]),minefields:this.clone(world?.minefields??[]),wallEdges:this.clone(world?.wallEdges??[])},reinforcements:{arrivedGroups:[...(reinforcementSystem?.arrivedGroups??[])],arrivalLog:this.clone(reinforcementSystem?.arrivalLog??[])},scenario:scenario?this.clone(scenario):null};}
 write(key,state){const snap=this.createSnapshot(state);localStorage.setItem(key,JSON.stringify(snap));return snap;} read(key){const raw=localStorage.getItem(key);if(!raw)return null;try{return JSON.parse(raw);}catch(e){console.error('[存档] 损坏',e);return null;}}
 save(slot,state){return this.write(this.key(slot),state)} load(slot){return this.read(this.key(slot))} has(slot){return localStorage.getItem(this.key(slot))!==null} remove(slot){localStorage.removeItem(this.key(slot))}
 autoSave(state){return this.write(this.autoKey,state)} loadAutoSave(){return this.read(this.autoKey)} hasAutoSave(){return localStorage.getItem(this.autoKey)!==null}
 saveResume(state){return this.write(this.resumeKey,state)} loadResume(){return this.read(this.resumeKey)} hasResume(){return localStorage.getItem(this.resumeKey)!==null} clearResume(){localStorage.removeItem(this.resumeKey)}
 getSummary(slot){const s=this.load(slot);return s?this.summary(s):null} getAutoSummary(){const s=this.loadAutoSave();return s?this.summary(s):null} summary(s){return{scenarioName:s.scenarioName??'战役',playerFaction:s.playerFaction,turn:s.turn?.turn??1,savedAt:s.savedAt,version:s.version}}
 exportSnapshot(s,filename='frontline-save.json'){const b=new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)} exportSlot(slot){const s=this.load(slot);if(!s)return false;this.exportSnapshot(s,`${s.scenarioName??'战役'}_第${s.turn?.turn??1}回合.json`);return true} async importFile(file,slot){const s=JSON.parse(await file.text());if(!s||!Array.isArray(s.units)||!s.version)throw new Error('无效存档');localStorage.setItem(this.key(slot),JSON.stringify(s));return s}
}
